### ISSUE TITLE
[SUGGESTION] Add "rotation" and "angle" arg

### ISSUE THREAD

**Issue by envizar** [ShaneBeee/SkBriggy#10]
### Suggestion

Add "rotation" and "angle" arg
It will be very useful for me

### Alternatives

�

### Additional Information

https://minecraft.wiki/w/Argument_types#rotation
https://minecraft.wiki/w/Argument_types#angle

**Comment by envizar** [comment]
Shane, can you at least add "Enhancement" label? I doubt that this idea was noticed

**Comment by ShaneBeee** [comment]
I can do angle -> https://commandapi.jorel.dev/9.2.0/argument_angle.html
but I don't see anything for rotation

**Comment by envizar** [comment]
https://commandapi.jorel.dev/9.2.0/argument_rotation.html?highlight=rotation#rotation-arguments
Maybe this?

**Comment by ShaneBeee** [comment]
ah yes, thanks, I missed that one

**Comment by envizar** [comment]
So... Will it be added?

**Comment by ShaneBeee** [comment]
its marked as enhancement and I haven't closed it, so yeah it will be.
But there's no timelines.
