### ISSUE TITLE
[BUG] Brig command descriptions not available to Skript.

### ISSUE THREAD

**Issue by friyes** [ShaneBeee/SkBriggy#14]
### What happened?

When registering a brig command with a description section it seems like it just defaults to _A Mojang provided command._
Though this seems to only happen when getting it with Skript. Using /help seems to work correctly.

```
brig command /describedcommand:
	description: This is a description.
	trigger:
		send "hi" to command sender

command /getdescriptions:
	trigger:
		send description of command "describedcommand" to command sender
```

### Steps to reproduce

1. Register a brig command with a description.
2. Get the description using Skript.

### Expected behavior

The description I set in the description section of the brig command.

### SkBriggy Version

1.2.0

### Server Version

Paper 1.20.4 (git-Paper-496)

### Skript Info

Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
Skript's documentation can be found here: https://docs.skriptlang.org/
Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
Server Version: git-Paper-496 (MC: 1.20.4)
Skript Version: 2.8.4 (skriptlang-github)
Installed Skript Addons: 
  - skript-placeholders v1.6.0 (https://github.com/APickledWalrus/skript-placeholders)
  - SkBee v3.4.3 (https://github.com/ShaneBeee/SkBee)
  - SkJson v3.0.7 (https://www.skjson.xyz/)
  - SkBriggy v1.2.0
Installed dependencies: 
  - Vault v1.7.3-b131

**Comment by ShaneBeee** [comment]
Brig commands are not registered the same as Bukkit based commands (the ones Skript uses), they're registered the same way Minecraft registers commands.
Unfortunately this is out of my control.
