### ISSUE TITLE
[SUGGESTION] Allow SkBriggy command registration to be used outside of brig command

### ISSUE THREAD

**Issue by JuceInUse** [ShaneBeee/SkBriggy#15]
### Suggestion

I think it would be nice if, with SkBriggy, you could make the registration of commands doable based on the state of the prior tab argument. For example, say you wanted a command like /claim <add|remove|list>. While you may want "add" and "remove" to be followed by an argument, you wouldn't want list to be followed by an argument. It would be nice, then, to be able to check the previous argument with brig-arg-number instead of only being able to use that in trigger and arg registration

Current attempted code:
```
on tab complete of "testbriggy":
	if any:
		event-string is "1"
		event-string is "one"
	then:
		register string arg "test":
			apply suggestions "2","3","4" if event-string is "1"
			apply suggestions "two","three","four" if event-string is "one"
```

This is the closest I have been able to get

### Alternatives

It would be a lot simpler if you instead allowed brig-arg-number to be used outside of the argument section as you could then register arguments entirely based on the previous argument. This same code would then look like this:
```
brig command /testbriggy <string>:
    arguments:
        set suggestions of arg 1 to "1","one"
        if any:
            brig-arg-1 is "1"
            brig-arg-1 is "one"
        then:
            register string arg "test":
                apply suggestions "2","3","4" if brig-arg-1 is "1"
                apply suggestions "two","three","four" if brig-arg-1 is "one"
    trigger:
```

**Comment by ShaneBeee** [comment]
👀 
<img width="1452" alt="Screenshot 2024-05-03 at 8 09 42 PM" src="https://github.com/ShaneBeee/SkBriggy/assets/20008482/dfb78071-3821-4fcf-8e04-0689f941d8d4">

**Comment by JuceInUse** [comment]
Yes, I am aware of that! However, it can only be used when registering an argument. I am asking for it to be able to be used OUTSIDE of that area. This would allow for the registration of arguments dependent on the previous tab completion rather than for the tab completion to simply be based on the previous tab completion

**Comment by ShaneBeee** [comment]
yeah, im sorry but that won't be happening.
The command has to be created and args done all at the same time.
They can't be changed after registration.

**Comment by JuceInUse** [comment]
This can already be done with Skript commands, which is why I was asking. Is there any other potential method that could be implemented that would allow for this to also be done with SkBriggy commands, even if a little convoluted? I mean, vanilla and Skript commands can do it

**Comment by ShaneBeee** [comment]
Skript commands don't use the Brigadier command system.
As for vanilla commands, they're all setup during registration, which internally use the same code, but they use command trees.
CommandTrees allow you to register different arg sections based on what was previously typed.
They're still registered at load time, but the conditions decide which part of the tree to use based on the previous tree/arg.
Unfortunately thats not something that is easy to translate between Brigadier and Skript, due to the fact Skript does everything at runtime, and without an insane amount of loops and recursion its just not something that will end up in SkBriggy anytime soon.

**Comment by ShaneBeee** [comment]
command trees have now been added, I hope that helps you do what you need to do.
