### ISSUE TITLE
[SUGGESTION] Make time argument return timespan

### ISSUE THREAD

**Issue by envizar** [ShaneBeee/SkBriggy#3]
### Suggestion

Make time argument return timespan
I tried to use it's return as timespan, but it didn't work

### Alternatives

�

**Comment by ShaneBeee** [comment]
I purposely picked not to do timespan, due to the fact the ArgType has things like "d" (day - minecraft day)
so running the command `/c 1d` you would return a timespan of 20 minutes, which is going to be super confusing to people
