### ISSUE TITLE
[SUGGESTION] Change particle arg return

### ISSUE THREAD

**Issue by envizar** [ShaneBeee/SkBriggy#7]
### Suggestion

I am trying to create command to show particles using skript-particle
To get particle and its data I using brig command with argument <particle>
It returns object with strange class and it's not skbee particle
I can't use it to create custom skript-particle particle
So... Can you change its return to support skbee particledata or write how to use its return in the wiki?

### Alternatives

?

**Comment by ShaneBeee** [comment]
unbeknownst to me, apparently the argument returns a class called ParticleData.
I will look into a way to convert that to particle

**Comment by envizar** [comment]
I received some [errors](https://pastebin.com/XVjJNQ8a) after building and installing skBriggy jsr with new commits

**Comment by ShaneBeee** [comment]
it looks like your build isn't shading

**Comment by envizar** [comment]
Can you give me jar with it?

**Comment by ShaneBeee** [comment]
you can grab it from the actions
https://github.com/ShaneBeee/SkBriggy/actions/runs/6238543275
(scroll down to artifacts)

**Comment by envizar** [comment]
Thanks!

**Comment by ShaneBeee** [comment]
reopening, I don't close issues til I release
